/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EntryPossible {
  description?: string | null;
  displayName?: string | null;
  key?: string | null;
}
