/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntryPossible } from '../models/entry-possible';
import { EntryUnitType } from '../models/entry-unit-type';
import { EntryValueType } from '../models/entry-value-type';
export interface EntryValue {
  current?: string | null;
  default?: string | null;
  isReadOnly?: boolean;
  possible?: Array<EntryPossible> | null;
  type?: EntryValueType;
  unitType?: EntryUnitType;
}
