/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum EntryUnitType {
  None = 'None',
  Password = 'Password',
  FilePath = 'FilePath',
  DirectoryPath = 'DirectoryPath',
  Flags = 'Flags',
  Base64 = 'Base64'
}
